"""Initial

Revision ID: 34bbe45365fc
Revises: 0481c6abad75
Create Date: 2022-06-27 12:18:31.819732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bbe45365fc'
down_revision = '0481c6abad75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_unit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('OFFER', 'CATEGORY', name='shopunittype'), nullable=True),
    sa.Column('parentId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['shop_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_unit')
    # ### end Alembic commands ###
