"""Initial 1

Revision ID: 7465be787510
Revises: 34bbe45365fc
Create Date: 2022-06-27 12:52:32.590937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7465be787510'
down_revision = '34bbe45365fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
