"""empty message

Revision ID: 7830d60498c4
Revises: e162c2d87fd3
Create Date: 2022-06-27 15:19:17.329838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7830d60498c4'
down_revision = 'e162c2d87fd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_unit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('OFFER', 'CATEGORY', name='shopunittype'), nullable=True),
    sa.Column('parentId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['shop_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_unit_version',
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('price', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('type', sa.Enum('OFFER', 'CATEGORY', name='shopunittype'), autoincrement=False, nullable=True),
    sa.Column('parentId', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_shop_unit_version_end_transaction_id'), 'shop_unit_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_shop_unit_version_operation_type'), 'shop_unit_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_shop_unit_version_transaction_id'), 'shop_unit_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_shop_unit_version_transaction_id'), table_name='shop_unit_version')
    op.drop_index(op.f('ix_shop_unit_version_operation_type'), table_name='shop_unit_version')
    op.drop_index(op.f('ix_shop_unit_version_end_transaction_id'), table_name='shop_unit_version')
    op.drop_table('shop_unit_version')
    op.drop_table('shop_unit')
    # ### end Alembic commands ###
