"""Initial

Revision ID: 99bb79cba622
Revises: e941d136e3ee
Create Date: 2022-06-27 12:07:40.567948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bb79cba622'
down_revision = 'e941d136e3ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
