"""empty message

Revision ID: db92b05dbe7a
Revises: 7ab34506fb17
Create Date: 2022-06-28 10:27:10.776904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db92b05dbe7a'
down_revision = '7ab34506fb17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_unit', sa.Column('name_2', sa.String(), nullable=True))
    op.add_column('shop_unit_version', sa.Column('name_2', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_unit_version', 'name_2')
    op.drop_column('shop_unit', 'name_2')
    # ### end Alembic commands ###
