"""empty message

Revision ID: e62845966e7f
Revises: db92b05dbe7a
Create Date: 2022-06-28 10:27:42.479843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62845966e7f'
down_revision = 'db92b05dbe7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_unit', 'name_2')
    op.drop_column('shop_unit_version', 'name_2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_unit_version', sa.Column('name_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shop_unit', sa.Column('name_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
