"""Initial

Revision ID: e84b6e1ce543
Revises: 2eeeee9f26b9
Create Date: 2022-06-26 21:25:00.077209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84b6e1ce543'
down_revision = '2eeeee9f26b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
