"""Initial

Revision ID: e941d136e3ee
Revises: e84b6e1ce543
Create Date: 2022-06-27 11:27:46.756158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e941d136e3ee'
down_revision = 'e84b6e1ce543'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
